"""initial database migration!

Revision ID: 027030d8eb03
Revises: 
Create Date: 2022-04-22 00:31:18.267279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027030d8eb03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_ip', sa.String(length=255), nullable=False),
    sa.Column('generation_time', sa.DateTime(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
